name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs: 
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-22.15.0-chrome-135.0.7049.114-1-ff-137.0.2-edge-135.0.3179.85-1
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}  
        env: 
          CYPRESS_RECORD_KEY: c516e494-dccb-4476-a92c-eba974b37db9
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-22.15.0-chrome-135.0.7049.114-1-ff-137.0.2-edge-135.0.3179.85-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}  
        env: 
          CYPRESS_RECORD_KEY: c516e494-dccb-4476-a92c-eba974b37db9
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
  cypress-e2e-edge:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-22.15.0-chrome-135.0.7049.114-1-ff-137.0.2-edge-135.0.3179.85-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: edge
          record: true
          group: UI Edge
          spec: ${{ github.event.inputs.spec }}  
        env: 
          CYPRESS_RECORD_KEY: c516e494-dccb-4476-a92c-eba974b37db9
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
